### ISSUE TITLE
Juju register failing with public address

### ISSUE THREAD

**Issue by kajgm** [juju/juju#21452]
### Description

After adding a new user on the controller via `juju add-user` and `juju grant user read my-model`. I'm attempting to add the user via the public ip address (controller ca has been added to client).

When I perform the register command, I receive the following error:
```
juju register 192.168.135.21:17070
Enter a name for this controller: test
ERROR "user-" is not a valid user tag
```

### Juju version

3.6.12 on the client and controller

### Cloud

MAAS

### Expected behaviour

The juju register should proceed with asking for user login credentials and/or successfully register the client to the controller.

### Reproduce / Test

(On controller)
juju add-user bob

(On client)
juju register <controller_public_ip>:<controller_port>

**Comment by kajgm** [comment]
This is also occurring after updating client and controller to 3.6.12. I notice this in the debug log when attempting to register:
```
juju register 192.168.135.21:17070 --debug
16:32:06 INFO  juju.cmd supercommand.go:56 running juju [3.6.12 d8a727fd219fea140f915a24ac267cc7b64e751a gc go1.25.4]
16:32:06 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/33252/bin/juju", "register", "192.168.135.21:17070", "--debug"}
Enter a name for this controller: maas-controller
16:33:18 DEBUG juju.api apiclient.go:1089 successfully dialed "wss://192.168.135.21:17070/api"
16:33:18 INFO  juju.api apiclient.go:610 connection established to "wss://192.168.135.21:17070/api"
16:33:18 DEBUG juju.cmd.loginprovider tryinorderloginprovider.go:53 login error using provider 0 - both client id and client secret must be set
16:33:18 DEBUG juju.cmd.loginprovider tryinorderloginprovider.go:53 login error using provider 1 - this version of Juju does not support login from old clients (not supported) (not supported)
16:33:18 DEBUG juju.cmd.loginprovider tryinorderloginprovider.go:53 login error using provider 2 - "user-" is not a valid user tag
ERROR "user-" is not a valid user tag
16:33:18 DEBUG cmd supercommand.go:571 error stack: 
"user-" is not a valid user tag
github.com/juju/juju/rpc.(*Conn).Call:178: 
github.com/juju/juju/api.(*state).APICall:1191: 
github.com/juju/juju/api.(*legacyLoginProvider).Login:168: 
github.com/juju/juju/cmd/internal/loginprovider.(*tryInOrderLoginProviders).Login:61: 
github.com/juju/juju/api.loginWithContext:267: 
github.com/juju/juju/api.Open:204: 
github.com/juju/juju/cmd/juju/controller.(*registerCommand).publicControllerDetails:301: 
github.com/juju/juju/cmd/juju/controller.(*registerCommand).run:202: 
```

**Comment by wallyworld** [comment]
This is due to changes added client side to refactor the login workflow.
Specifically, an empty user tag is being stringified here 
https://github.com/juju/juju/blob/4854b26031f8c625c8769677ab8f6b9d27d101c1/api/legacyloginprovider.go#L135
and the result is "user-" which is not valid and results in an error server side.

**Comment by jujubot** [comment]
This bug has now been triaged.
[JUJU-8980](https://warthogs.atlassian.net/browse/JUJU-8980)

[JUJU-8980]: https://warthogs.atlassian.net/browse/JUJU-8980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kian99** [comment]
Hi @kajgm,

I'm taking a look at this issue. 

Reading `juju register -h` it seems that the command should either be called with a registration string obtained from `juju add-user` e.g. `juju register MFATA3JvZDAnExMxMDQuMTU0LjQyLjQ0OjE3MDcwExAxMC4xMjguMC4yOjE3MDcwBCBEFCaXerhNImkKKabuX5ULWf2Bp4AzPNJEbXVWgraLrAA=`.

Or it can be used with an address like `juju register public-controller.example.com` if the controller is configured with an external identity provider.

But `juju register 192.168.135.21:17070` with an IP address doesn't seem like the right syntax here.

There was a [similar issue](https://github.com/juju/juju/issues/21045) for `juju login` which was fixed and I think will accomplish what you're after.

Something like `juju login -c test 192.168.135.21:17070 -u bob` should do the trick. I've tested this with 3.6.12 and it works, it will prompt you for a password.

Let us know if that solves it for you. 

Also, let us know if this was an issue introduced only in 3.6.12. I've tested it with 3.6.11 and I'm seeing the same issue so I think it's likely that this behaviour has been this way for a while.
```
$ juju version
3.6.11-ubuntu-amd64
$ juju register 10.248.83.239:17070
Enter a name for this controller: test
ERROR "user-" is not a valid user tag
```

**Comment by wallyworld** [comment]
@kian99 We should look to clean things up so that the client does not end up sending an invalid empty "user-" tag string. Sounds like we need to better validate args to register and fail before we send bad input.

**Comment by kajgm** [comment]
Hi @kian99 

Thanks for taking a look into this. I think I realize now that there is just a slight gap in current capabilities/documentation here, rather than a bug.

I've taken another look at the documentation on juju register and noticed this line

"When adding a controller at a public address, authentication via some external third party (for example Ubuntu SSO) will be required, usually by using a web browser."

Which I did not initially realize was the case.

A bit of background on the exact end goal of what I'm trying to achieve here might help.
I have a controller within a private subnet, hosted on AWS EKS. The api server (and controller) is exposed via a cluster endpoint so that I can access the cluster externally.

When I perform a juju add-user, it provides me with a registration string that contains an address within this private subnet.
Therefore, when I go to register my client with this controller, it fails as it's trying to use the internal ip address, rather than the endpoint configured via AWS.

```
juju register <registration_string>
Enter a new password:
Confirm password:
Enter a name for this controller [my-controller]:
Initial password successfully set for test-user.
ERROR cannot connect to k8s api server; try running 'juju update-k8s --client <k8s cloud name>': starting proxy for api connection: connecting k8s proxy: Get "https://<internal_ip>/api/v1/namespaces/controller-my-controller/services/controller-service": dial tcp <internal_ip>: i/o timeout
```

It is possible to work around this after this initial failed registration, by modifying the .local/share/juju/controllers.yaml file from this:
```
...
proxy-config:
type: kubernetes-port-forward
config:
api-host: <internal-ip>
...
```

To this:

```
...
proxy-config:
type: kubernetes-port-forward
config:
api-host: <cluster_api_endpoint>
...
```

However, this isn't a great workflow.
`juju update-k8s --client` only works for the underlying cloud, not the controller(?).
`juju register <public_hostname>` also doesn't seem to work due to this failed authentication issue.
I don't think `juju login -c test 192.168.135.21:17070 -u bob` is quite right either, as the user hasn't yet had a chance to set a password, and at least for me this automatically fails with a `ERROR cannot log into "<controller address>": invalid entity name or password`.

As far as I can tell, there's no way to also configure this with controller settings using `juju controller-config`.

My test shows a local ip as I was attempting to test this in my own environment with isolated subnets. It is possible that `juju register <public_hostname>` may work for my EKS cluster if it uses AWS' third party authentication. I have not had a chance to test this quite yet.

Regardless, this might just be a case of needing to clarify some documentation or improve the error logging when trying it this way as @wallyworld suggests.
